title: Fostering AI Research (FAIR)
email: k.m.rajpoot@bham.ac.uk
description: University of Birmingham Dubai
author: Dr Ruchit Agrawal
url: "https://rragrawal.github.io/fair/"

logo:
  normal: "/fair/img/logos/uobd.png"
  inverted: "/fair/img/logos/uobd2.jpg"

# Social Profiles
twitter_username: birminghamdubai

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
background_color: "#205cac"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
